import { Familjen_Grotesk } from "next/font/google";
import "./globals.css";
import Cursor from "@/components/Cursor";

const familjen = Familjen_Grotesk({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Armur clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={familjen.className}>
        <Cursor />
        {children}
      </body>
    </html>
  );
}
